import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-8">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-7">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about2">about 2</Link>
            </li>
            <li>
              <Link href="/blogs">blogs</Link>
            </li>
            <li>
              <Link href="/post">posts</Link>
            </li>
          </ul>
        </nav>
        <hr />
        {children}
        <footer>sifat all right</footer>
      </body>
    </html>
  );
}
